# general settings
name: train_DRCT_SRx4_finetune_from_DRCT_pre-train_with_DACLIP_modify_v2
model_type: DRCTModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: MySet
    type: PairedImageDataset
    dataroot_gt: /swim-pool/yicheng/NYCU_VRDP_FinalProject/dataset/train/hr
    dataroot_lq: /swim-pool/yicheng/NYCU_VRDP_FinalProject/dataset/train/lr
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 3
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # val_1:
  #   name: Set5
  #   type: PairedImageDataset
  #   dataroot_gt: /work/u1657859/DRCT/datasets/Set5/GTmod12/
  #   dataroot_lq: /work/u1657859/DRCT/datasets/Set5/LRbicx4/
  #   io_backend:
  #     type: disk

  # val_2:
  #   name: Set14
  #   type: PairedImageDataset
  #   dataroot_gt: /work/u1657859/DRCT/datasets/Set14/GTmod12/
  #   dataroot_lq: /work/u1657859/DRCT/datasets/Set14/LRbicx4/
  #   io_backend:
  #     type: disk

# network structures
network_g:
  type: DRCT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# # no pre-trained weight
# path:
#   pretrain_network_g: ~  #pretrained weight
#   strict_load_g: true
#   resume_state: ~

path:
  pretrain_network_g: /swim-pool/yicheng/NYCU_VRDP_FinalProject/experiments/train_DRCT_SRx4_finetune_from_DRCT_pre-train_with_DACLIP_modify/models/net_g_120000.pth
  param_key_g: 'params_ema'
  strict_load_g: False
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [30000, 600000, 90000, 120000, 150000, 165000, 180000, 195000, 210000, 225000, 240000]
    gamma: 0.5


  total_iter: 500000
  warmup_iter: 3000  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: false

  # metrics:
  #   psnr:
  #     type: calculate_psnr
  #     crop_border: 3
  #     test_y_channel: true
  #     better: higher
  #   ssim:
  #     type: calculate_ssim
  #     crop_border: 3
  #     test_y_channel: true
  #     better: higher
  metrics: {}

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# distributed training
dist_params:
  backend: nccl
  port: 29500
